services:

  db:
    image: postgres:17.4-alpine
    shm_size: 128mb
    volumes:
      - ./.docker/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}

  valkey:
    image: valkey/valkey:8.0.2-alpine

  minio:
    image: bitnami/minio:2025.3.12
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - ./.docker/minio:/bitnami/minio/data

  rabbitmq:
    image: rabbitmq:4.0.7-alpine
