services:
  gateway:
    environment:
      - GRPC_AUTH_SERVER=auth:50052
      - GRPC_ROOM_SERVER=rooms:50051
      - GRPC_USER_SERVER=users:50053

      - REDIS_CONNECTION=${REDIS_CONNECTION}
    build:
      context: .
      target: gateway
    ports:
      - 3000:3000
    depends_on:
      - auth
      - redis
      - users

  auth:
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}

      - PG_PASSWORD=${PG_PASSWORD}
      - PG_USER=${PG_USER}
      - PG_DB=${PG_DB}

      - PG_HOST=db
      - PG_PORT=5432
    build:
      context: .
      target: auth
    depends_on:
      - db

  users:
    environment:
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_USER=${PG_USER}
      - PG_DB=${PG_DB}

      - PG_HOST=db
      - PG_PORT=5432
    build:
      context: .
      target: users
    depends_on:
      - db

  db:
    image: postgres:17.4-alpine
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}

  redis:
    image: redis:8.0-alpine
    # minio:
    #   image: quay.io/minio/minio
    #   ports:
    #     - 19000:9000
    #     - 19001:9001
    #   environment:
    #     MINIO_ROOT_USER: ${MINIO_USER}
    #     MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    #   volumes:
    #     - ./.docker/minio:/data
    #   command: server --console-address ":9001" /data
