name: Check Types

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout
        run: npm ci
      - name: Check Types
        run: npx tsc --noEmit
